### ISSUE TITLE
how shoud i assign a k8s endpoint for this plugin?

### ISSUE THREAD

**Issue by strahe** [geofeedia/drone-k8s#2]
Hi, i  am using rancher with k8s, in rancher, the k8s API endpoint like 
`http://192.168.1.8:8080/v1/projects/1a5`
but this plugin only needs `k8s_service_host` and `k8s_service_port`?
any ideas?

**Comment by austenLacy** [comment]
@strahe hey just saw this.

You might be able to use `protocol`, `k8s_service_host`, and `k8s_service_port` to get that I believe. Though it does require a little hackery in that the port will also contain the rest of the URL.

```
protocol: http://
k8s_service_host: 192.168.1.8
k8s_service_port: 8080/v1/projects/1a5
```
